# Generated by Django 4.2.6 on 2023-10-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_orders_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
