# Generated by Django 4.2.6 on 2023-10-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
    ]
